require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ecommerce_app' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  pod 'RNPaypal', :path => '../node_modules/react-native-paypal'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  target 'ecommerce_appTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'ecommerce_app-tvOS' do
  # Pods for ecommerce_app-tvOS

  target 'ecommerce_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
